### ISSUE TITLE
Export function have moved

### ISSUE THREAD

**Issue by psu** [nntarasov/csv2keychain#1]
Big thanks, nice little tool, just what I needed. 
A small detail, [according to this comment](https://superuser.com/questions/164741/google-chrome-import-export-passwords#comment1782368_1144729) the export function in chrome have moved to [chrome://settings-frame/passwords](chrome://settings-frame/passwords)

**Comment by nntarasov** [comment]
Thanks for feedback
Noticeable issue, needs to be fixed
