### ISSUE TITLE
Not syncing with iCloud

### ISSUE THREAD

**Issue by d1slact0r** [nntarasov/csv2keychain#3]
All worked out well with the app, thanks. The only thing is that it is not synced to icloud. It's synced to the keychain "login" and therefor not picked up by the keychain "icloud" or "local". Is there anything I can do to make this work with iCloud?

**Comment by nntarasov** [comment]
Thank you for the feedback. Unfortunately, it seems that there is no known way access to iCloud keychain from this app. [Details](https://apple.stackexchange.com/questions/238296/dump-icloud-keychain-in-terminal)
The simplest way to export credential into iCloud keychain is to use it in Safari. If you will follow the login/password suggest in Safari on some website -- this pair of credentials will be exported to iCloud by Safari automatically. Does this way meet your requirements?

**Comment by bcrigler** [comment]
Ehh I take that back tried a few more and it doesn't sync to icloud...  think I just need to (like you said) import the csv from Chrome into Safari then it will sync it

**Comment by d1slact0r** [comment]
See my repository I made a easy working one. Does the job in few minutes.

**Comment by bcrigler** [comment]
Thanks!  I already updated to Firefox Quantum so going from Chrome -> Firefox -> Safari not as much of an option without installing an older Firefox version.

**Comment by d1slact0r** [comment]
no need for firefox. Just have chrome and safari ;) that is all
